EOF = "\0"

singinData_t = "singin"
singupData_t = "singup"
appendFriend_t = "append_f"
searchFriend_t = "search_f"
userExists_t = "user_e"
userNotExists_t = "user_ne"
userAdded_t = "user_a"
appendUser_t = "append_user"
requestSendMessage_t = "send_message"
removeFriend_t = "remove_friend"
newProfileImage_t = "set-profile-image"
updateUserImage_t = "update-user-image"